### ISSUE TITLE
Hyphens are not supported in unquoted strings (key names)

### ISSUE THREAD

**Issue by BitBrit** [yellowblood/hocon-js#11]
I have a need for a library just like yours but there a couple of issues. I'll create issues separately so they can be independently tracked.

I believe that hyphens should be allowed in an unquoted string if the hyphen isn't at the start. 

https://github.com/typesafehub/config/blob/master/HOCON.md#unquoted-strings

Right now the library produces:

Hocon:
```
hyphen-separated-name {}
```
Output:
```
ReferenceError: separated is not defined
```
Could you allow hyphens please?

**Comment by walshie4** [comment]
Just tried parsing some HOCON that starts with an unquoted string which contains hyphens and had no problem.  Might want to re-try this with the latest version.

Your example works as well.

**Comment by yellowblood** [comment]
Thanks @walshie4 !

**Comment by BitBrit** [comment]
Confirmed to work with latest! Thanks @walshie4
